language: cpp
compiler: g++
# Handle git submodules yourself
#git:
#    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - go get ADVRHumanoids/xbotcoremodel.git
    #- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    #- git submodule update --init --recursive
script: 
- cmake .
- make
#- ./mytest
#- make test
