# CENTAURO config
x_bot_interface:
  framework: "DUMMY"
  internal_model_type: "RBDL"
  is_internal_model_flaoting_base : "false"
  urdf_filename: "urdf/centauro_upperbody.urdf"
  srdf_filename: "srdf/centauro_upperbody.srdf"
  joint_map_config: "joint_map/centauro_test_joint_map_upperbody.yaml"


RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  joint_state_name: "/centauro/joint_states"
  joint_service_name: "/centauro/position_controller/get_joint_names"
  command_topic_name: "/centauro/position_controller/command"
  ft_topic_names: ["/ft_foot_1", "/ft_foot_2", "/ft_foot_3", "/ft_foot_4"]
  
RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"
