# CENTAURO config
x_bot_interface:
  framework: "ROS"
  internal_model_type: "RBDL"
  is_internal_model_flaoting_base : "true"
  urdf_filename: "urdf/centauro.urdf"
  srdf_filename: "srdf/centauro.srdf"
  joint_map_config: "joint_map/centauro_test_joint_map.yaml"


RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  joint_state_name: "/centauro/joint_states"
  joint_service_name: "/centauro/position_controller/get_joint_names"
  command_topic_name: "/centauro/position_controller/command"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"
