# WALKMAN config
x_bot_interface:
  framework: "YARP"
  internal_model_type: "RBDL"
  is_internal_model_flaoting_base : "false"
  urdf_filename: "urdf/bigman_fixed_hands.urdf"
  srdf_filename: "srdf/bigman_config.srdf"
  joint_map_config: "joint_map/bigman_ecat_joint_map.yaml"

RobotInterfaceYARP:
  subclass_name: "RobotInterfaceYARP"
  path_to_shared_lib: "libRobotInterfaceYARP.so"
  subclass_factory_name: "robot_interface_yarp"
  module_prefix: "test_YARP"
  # different config files for module_prefix

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"